### ISSUE TITLE
Exception "Could not sample hardware counters." thrown for Mali-T760 MP8

### ISSUE THREAD

**Issue by reubenscratton** [ARM-software/HWCPipe#56]
I run a lot of device farm tests and have seen this exception thrown by `MaliProfiler::sample_counters()` on the Samsung Galaxy S6, the Samsung Galaxy S6 Edge, and the Samsung Galaxy Note 5, all running Android 7.0. These devices all have the same GPU, the **Mali-T760MP8**.

Please advise & many thanks.

**Comment by abbaswasim** [comment]
Just to confirm are you running the following?

```
adb shell setprop security.perf_harden 0
```

**Comment by reubenscratton** [comment]
No am not doing that, we've never needed to do it - our code & hwcpipe works fine on all other devices, as far as I know. (We don't use CPU counters, only GPU, so no Meltdown/Spectre considerations).  I'll try it to see if it makes a difference though.

**Comment by reubenscratton** [comment]
Just tried it, it made no difference.

**Comment by abbaswasim** [comment]
Ok thanks for confirming. Sorry Not very helpful then. @solidpixel any thoughts.

**Comment by bengaineyarm** [comment]
Most likely this is because these few devices are quite old and predate the first Mali driver version that supported reading h/w counters via the public ioctl interface. IIRC this is Mali driver version `m_r12`, so if you are able to detect the driver version (which should be of the form `r<n>p<n>` (such as r12p0) this will help identify whether the driver is too old or not.

**Comment by reubenscratton** [comment]
Do 'r' and 'p' correspond to `MaliHWInfo::r_value` and `MaliHWInfo::p_value` as found in `vendor/arm/mali/mali_profiler.cpp` ?

**Comment by bengaineyarm** [comment]
IIRC, no, those r/p values refer to the revision of the hardware (so will likely read as something like r1p0)

**Comment by solidpixel** [comment]
For the Samsung devices, we only support Galaxy S7 onwards. 

Galaxy S6 will not work because the counters are not exposed due to a device manufacturer customization of the kernel driver.

I doubt we ever tested a Galaxy S5 - it predates HWCPipe, and is very likely on the older kernel IOCTL we don't support.

**Comment by solidpixel** [comment]
We should add a section on "supported devices/driver versions" to the project readme.txt.
